version: '3.1'

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  postgres-data:
  mysql-data:

services:

  drupal:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always

  mysql:
    image: mysql:5
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  postgres:
    image: postgres:10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    restart: always
